### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DataExplorerUser** [ianvet31/EntanglewareGUI#1]
Hi,

I work with the Dear PyGui team and I'm always interested in what gets built with that library, so I'm curious what the status of this project is. Could you clarify?

The repository does not contain a requirements.txt file, so it's not clear if the app can be run by others. Are all required modules on pypi?

**Comment by ianvet31** [comment]
Hello, sorry for the confusion. This was intended for my old quantum computing research group. We used DPG to create an experiment control GUI for testing and creating sequences of signals to send to experiment instruments; lasers, optical traps, AOMs and EOMs, etc. I believe it was used for initial testing but the project has been unfinished and on pause since Spring 2022 as it wasn't an urgent task for the group. It wasn't intended for others to use, I just put it on github to store it for potential future use.

**Comment by DataExplorerUser** [comment]
Ok, thanks for your explanation. That clarifies it.

In case you create an application with Dear PyGui in future and you'd like to share it, please let us know. We keep an [showcase overview ](https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase)of various apps, so that people can see what's possible.
